### ISSUE TITLE
Where is the source and at least a simple example of how to use the library?

### ISSUE THREAD

**Issue by greatbiggiantbrain** [NimaAra/Easy.Transport#1]
Yes, this is an easy to use WebSocket client, but at the very least, have a readme on how to make a simple connection.  For instance, can you look at the payload that is returned?

Thanks,
Brian

**Comment by NimaAra** [comment]
No it's not, this is an empty repository with nothing to offer :-)

**Comment by greatbiggiantbrain** [comment]
So it is not easy (your response to "no, it's not")?  and you will offer no clue how to use it?  Why even put it on Nuget then?  

Anyway, I'll look elsewhere.
Thanks
